# Hospitality Pipeline — Silver Layer (Clean & Validate)
# Module: Design and implement data pipelines
#
# Industry context:
#   Raw reservation data from StayWell Hotels' property-management systems
#   frequently contains nulls, negative amounts, and invalid status codes.
#   This Silver layer cleans and validates incoming records so the Gold
#   analytics layer only sees trusted, well-formed data.
#
# Demo objectives:
#   - Show Lakeflow expectations (WARN / DROP / FAIL) for data quality enforcement.
#   - Map the CLEAN & VALIDATE stage of the medallion architecture.
#   - Compare declarative expectations against writing manual validation code.
#
# How to use this file as a trainer demo:
#   1. Ensure 01_bronze_reservations.py is also included in the pipeline.
#   2. Run the pipeline and open the Data quality tab for silver_reservations.
#   3. Walk through pass/fail counts — point to the intentionally dirty rows
#      generated by setup_10.
#   4. Toggle between warn and drop to show the different behaviors.

from pyspark import pipelines as dp


# ─────────────────────────────────────────────
# Reusable rule dictionaries
#   Trainer: highlight how expect_all_or_drop allows rule reuse.
# ─────────────────────────────────────────────
RESERVATION_INTEGRITY_RULES = {
    "reservation_id_not_null": "reservation_id IS NOT NULL",
    "guest_id_not_null":        "guest_id IS NOT NULL",
    "property_id_not_null":     "property_id IS NOT NULL",
}

RESERVATION_DATE_RULES = {
    "check_in_not_null":        "check_in_date IS NOT NULL",
    "check_out_not_null":       "check_out_date IS NOT NULL",
    "check_out_after_check_in": "check_out_date >= check_in_date",
    "not_future_booked_over_2y":"check_in_date <= date_add(current_date(), 730)",
}

RESERVATION_AMOUNT_RULES = {
    "positive_total_amount":    "total_amount > 0",
    "reasonable_total_amount":  "total_amount <= 50000",
}


# ─────────────────────────────────────────────
# DEMO 2A: Warn action — all records pass through, violations logged
#   Trainer: "This is useful for monitoring quality trends before deciding
#   how aggressive to be with drop/fail rules."
# ─────────────────────────────────────────────
@dp.table(
    comment=(
        "Silver reservations — warn action: violations logged, "
        "all records retained. Use for initial quality baselining."
    )
)
@dp.expect("reservation_id_present", "reservation_id IS NOT NULL")
@dp.expect("positive_amount",        "total_amount > 0")
@dp.expect("valid_status",
           "status IN ('confirmed', 'checked_in', 'checked_out', 'cancelled')")
def silver_reservations_warn():
    return spark.readStream.table("LIVE.bronze_reservations")


# ─────────────────────────────────────────────
# DEMO 2B: Drop action — invalid rows removed, clean rows pass through
#   Trainer: Walk through the Data quality tab — show exactly how many
#   records were dropped and why.
# ─────────────────────────────────────────────
@dp.table(
    comment=(
        "Silver reservations — drop action: invalid rows removed. "
        "This is the table Gold layer tables will read from."
    )
)
@dp.expect_all_or_drop(RESERVATION_INTEGRITY_RULES)
@dp.expect_all_or_drop(RESERVATION_DATE_RULES)
@dp.expect_all_or_drop(RESERVATION_AMOUNT_RULES)
@dp.expect_or_drop(
    "valid_status",
    "status IN ('confirmed', 'checked_in', 'checked_out', 'cancelled')"
)
@dp.expect_or_drop(
    "valid_room_type",
    "room_type IN ('standard', 'deluxe', 'suite', 'executive')"
)
def silver_reservations():
    return spark.readStream.table("LIVE.bronze_reservations")


# ─────────────────────────────────────────────
# DEMO 2C: Fail action — critical integrity constraint that must never be violated
#   Trainer: "This stops the pipeline immediately. Use when data corruption
#   would produce incorrect analytics that reach business decision-makers."
# ─────────────────────────────────────────────
@dp.table(
    comment=(
        "Silver guests — fail action on null guest_id: "
        "any record without an identity stops the pipeline."
    )
)
@dp.expect_or_fail("guest_id_must_exist", "guest_id IS NOT NULL")
@dp.expect_or_drop("valid_email",
                   "email RLIKE '^[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}$'")
@dp.expect_or_drop("positive_loyalty_points", "loyalty_points >= 0")
def silver_guests():
    return spark.readStream.table("LIVE.bronze_guests")
